### ISSUE TITLE
Assign the value on click select, not on click outside

### ISSUE THREAD

**Issue by kuatroka** [maxjerry0107/svelte-autocomplete-input#2]
Hi, how would I get the console to print the full value (and not the partial) on selecting/clicking on the item in the list and not when clicking outside the text box?
I tried to change `on:blur` to `on:click` or input or submit, but it doesn't seem to work.  See the gif. 
![autocomplete](https://github.com/maxjerry0107/svelte-autocomplete-input/assets/9093546/9ac07ec8-acfc-447b-aa33-03b9a2af658a)
Thanks

**Comment by maxjerry0107** [comment]
Thank you for your feedback.
Release a new version [v1.0.2](https://github.com/maxjerry0107/svelte-autocomplete-input/releases/tag/v1.0.2).
Fixed issue adding new handler. onChangeValue
